### ISSUE TITLE
Lexical error when attempting download data via DoubleClick Search API

### ISSUE THREAD

**Issue by Curtis-Cochran** [MarkEdmondson1234/googleAuthR#18] opened 2016-02-13 00:38 UTC
I've been using googleAuthR to retrieve synchronous data through the DoubleClick Search API and it's working great however when I try to pull reports using the Asynchronous method, I'm having trouble with the last step...

In order to get asynchronous reports, you have to use Reports.Request() to request the report and get the reportid, then use Reports.Get() to get the status and URL of the report data, and then a third method Reports.getFiles() to actually download the data.

[https://developers.google.com/doubleclick-search/v2/how-tos/reporting/asynchronous-requests]

It's the last step that I'm having trouble with. I'm getting the following error when I try to pull the data down. I think it's because the data is not in JSON format (it's in CSV), and the JSON parser can't handle it. Is there a way to just retrieve the data without it trying to parse it out via JSON?

Here's the error I"m getting:

Error: lexical error: invalid char in json text.
                                       agencyId,advertiserId,clicks,im
                     (right here) ------^

If I test the script in Google API Explorer, it pulls the data down in a comma separated format rather than JSON for this particular method.

I've tried to retrieve it using httr or RCurl but I'm not that versed in it so I'm not sure what parameters are required.

Thanks,

Curtis

**Comment by MarkEdmondson1234** [comment] 2016-02-13 00:49
Hi Chris, great use case and something I may need to do myself one day so very interested in getting it sorted.  

Yes it may be as DoubleClick isn't using JSON, but could you let me know where the error occurs? (where does the above message get called from?)  

I'm guessing it is in the `checkGoogleAPIError()`line: `ga.json <- httr::content(req, as = "text", type = "application/json", encoding = "UTF-8") `

There is an option in the package to handle non-JSON files but I've not had a use case yet to test it, this may be it :) It should be viewable at `getOption("googleAuthR.ok_content_types")` - could you also just confirm that setting?

**Comment by Curtis-Cochran** [comment] 2016-02-13 15:41
Hi Mark,

Thanks for the assistance. 

When I traceback, this is what it returns:

` Error: lexical error: invalid char in json text.
                                       agencyId,advertiserId,clicks,im
                     (right here) ------^ 
7 parse_string(txt, bigint_as_char) 
6 parseJSON(txt, bigint_as_char) 
5 fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, 
    simplifyMatrix = simplifyMatrix, flatten = flatten, ...) 
4 jsonlite::fromJSON(ga.json) 
3 checkGoogleAPIError(req) 
2 doHttrRequest(req_url, shiny_access_token, http_header, the_body, 
    customConfig) 
1 adGroup.download.request() `

When I checked `getOption("googleAuthR.ok_content_types")` the following was returned: 

[1] "application/json; charset=UTF-8" "text/html; charset=UTF-8" 

Thanks,

Curtis

**Comment by MarkEdmondson1234** [comment] 2016-03-17 14:40
Curtis if you are still there, this could be fixed now in the latest version from github.

For the CSV download call, you need to set the option to accept text/csv:

`option("googleAuthR.ok_content_types" = c("text/csv: charset=UTF-8","application/json; charset=UTF-8" "text/html; charset=UTF-8"))`

It will then skip the JSON check when you call your function.

**Comment by MarkEdmondson1234** [comment] 2016-04-16 21:35
@Curtis-Cochran are you there to see if this works now?

**Comment by Curtis-Cochran** [comment] 2016-04-16 22:19
Hi Mark,

Thanks for the update. I'll test it out and report back.

Curtis

**Comment by Curtis-Cochran** [comment] 2016-04-19 11:42
I loaded up version 0.2.0.9000 from Github and tried it again, but am getting the same error:

Error: lexical error: invalid char in json text.

I modified the code you provided above slightly because it was throwing a syntax error. This is how I'm setting the googleAuthR.ok_content_types option:

`options("googleAuthR.ok_content_types" = c("text/csv; charset=UTF-8",
                                          "application/json; charset=UTF-8", 
                                          "text/html; charset=UTF-8"))`

I've been using R to generate the report and retrieve the reportid and then I call some python code to actually read the csv file in. It's a workaround but I have it working. It seems I just need a way to read the csv directly as there is no request/response for this endpoint.

Thanks,
Curtis

**Comment by MarkEdmondson1234** [comment] 2016-05-08 21:14
Hi @Curtis-Cochran - glad you have a working workflow, but just to try and address this in case other problems occur:

In the latest version I have a new flag `option("googleAuthR.rawResponse")`

Defaults to FALSE, but if you set it to TRUE (`option("googleAuthR.rawResponse" = TRUE)`) then it should skip the JSON checks in the response and return raw content, which should solve your issue.

**Comment by samfield** [comment] 2016-06-07 23:02
This might still be valid. At least I countered similar behavior with drive API usage.

I wasn't able to set the options with the mentioned rawResponse. If I understand correctly setting the option to TRUE isn't respected. There are couple of references in the source where options are referred as option rather than plural but I think they were only in comments. So shouldn't be a typo issue either.

I'm unsure if my assignement is with the correct format of text/txt but setting that didn't remove the root problem for me when using the Drive API. lexical errors are still reported.



```
library(googleAuthR)
#set to raw response
options("googleAuthR.rawResponse" = TRUE)
#check if changed
getOption("googleAuthR.ok_content_types")
#maybe no change:
#[1] "application/json; charset=UTF-8"
#[2] "text/html; charset=UTF-8"

#try to set manually       
options("googleAuthR.ok_content_types" = c("text/txt; charset=UTF-8"))
#check
getOption("googleAuthR.ok_content_types")
#at least the value changed, assuming that format is correct this should work
#[1] "text/txt; charset=UTF-8"

#Next to produce a lexical error
#OBS!! since issue 36 prevents gar_auth() method for authentication I use httr to set token

#set up credentials by using an app
oauth_endpoints("google")

myapp <- oauth_app("google",
                   key = "yourkey.apps.googleusercontent.com",
                   secret = "yoursecret")

#this will complete the oauth flow provided the endpoints, keys and secret are correct
google_token <- oauth2.0_token(oauth_endpoints("google"),
                               myapp,
                               scope = "https://www.googleapis.com/auth/drive")
#set token for googleAuthR
#another way would be to use the googleAuthR native gar_auth() but unable to use it for drive v3 at the moment
gar_auth(token = google_token)

#use API

#get file ids
f_get_id <- gar_api_generator(baseURI = "https://www.googleapis.com/drive/v3/files", 
                              http_header = "GET",
                              pars_args = list(q= "name = 'your_text_or_csv.txt'")) 
response_file <- f_get_id()
#get the download candidate IDs
download_candidates <- response_file$content$files$id

#download first file of the candidates
f_content <- gar_api_generator(baseURI = paste0("https://www.googleapis.com/drive/v3/files/",download_candidates[1]), 
                               http_header = "GET",
                               pars_args = list(alt= "media", acknowledgeAbuse = "TRUE")) 
getOption("googleAuthR.ok_content_types")#check for option types

content_file <- f_content()
#with me this fails with:
#Error: lexical error: invalid char in json text.
# <your content in the file>
# (right here) ------^

```
Maybe this would also be a Stackoverflow thing but lexical error was reported here also. So decided to flood the thread.

```
sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] googleAuthR_0.3.0

loaded via a namespace (and not attached):
[1] tools_3.3.0
> library(httr)
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] httr_1.1.0        googleAuthR_0.3.0

loaded via a namespace (and not attached):
[1] R6_2.1.2    tools_3.3.0
```

**Comment by MarkEdmondson1234** [comment] 2016-06-08 06:50
@samfield I think this is a separate issue to the authentication not using the native `gar_auth` and the correct scopes, which are used in `gar_api_generator` later as well.  With correct auth, from your example in https://github.com/MarkEdmondson1234/googleAuthR/issues/36 the content is available via `responsefile$content`

**Comment by MarkEdmondson1234** [comment] 2016-06-22 11:08
Ok @Curtis-Cochran I got to work with a reproducible example so think this is now really really fixed.  

Set  `options(googleAuthR.rawResponse = TRUE)` before the `gar_api_generator` call (then set it back again if you want it for other functions.  

The content is returned in raw form, which you can then use `httr::content()` to parse yourself.

**Closed** 2016-06-22 11:08 UTC
Labels: bug

**Comment by MarkEdmondson1234** [comment] 2016-06-22 11:11
Here is an example I had the error for google cloud storage, that got the error when trying to download a .csv

```
gcs_get_object <- function(bucket, object_name){
  
  options(googleAuthR.rawResponse = TRUE)

  message("raw response> ", getOption("googleAuthR.rawResponse"))

  ob <- googleAuthR::gar_api_generator("https://www.googleapis.com/storage/v1/",
                                       path_args = list(b = bucket,
                                                        o = object_name),
                                       pars_args = list(alt = "media"))
  req <- ob()

  options(googleAuthR.rawResponse = FALSE)

  req$content
  
}
```

**Comment by Curtis-Cochran** [comment] 2016-06-22 11:18
Great. I'll take a look from my end and post back the results. Thanks!

Curtis

**Comment by MarkEdmondson1234** [comment] 2016-06-22 11:42
This is an example saving the csv to disk:

```r
gcs_get_object <- function(bucket, 
                           object_name, 
                           meta = FALSE,
                           saveToDisk = NULL){
  
  testthat::expect_type(bucket, "character")
  testthat::expect_type(object_name, "character")
  testthat::expect_length(bucket, 1)
  testthat::expect_length(object_name, 1)  
  
  if(meta){
    alt = "" 
  } else {
    options(googleAuthR.rawResponse = TRUE)
    alt = "media"
  }

  message("raw response> ", getOption("googleAuthR.rawResponse"))
  ob <- googleAuthR::gar_api_generator("https://www.googleapis.com/storage/v1/",
                                       path_args = list(b = bucket,
                                                        o = object_name),
                                       pars_args = list(alt = alt))
  req <- ob()
  options(googleAuthR.rawResponse = FALSE)
  
  if(!is.null(saveToDisk)){
    
    bin <- httr::content(req, "raw")
    writeBin(bin, saveToDisk)
    message("Saved ", object_name, " to ", saveToDisk)
    out <- TRUE
    
  } else {
    message("Downloaded ", object_name)
    out <- req
  }
  
  out
  
}
```

**Comment by shariharan99** [comment] 2016-07-19 22:02
I'm using an updated version of your googleCloudStorageR repo (downloaded today) and the gcs_get_object function matches the one in the post above this but I'm still getting a json error:

Request Status Code: 404
Error: lexical error: invalid char in json text.
                                       Not Found
                     (right here) ------^

**Comment by MarkEdmondson1234** [comment] 2016-07-20 08:20
Thanks for the report, this could be a lot of things so would you mind reporting it on the repository URL https://github.com/cloudyr/googleCloudStorageR/issues with some reproduceable code and your session info?

**Comment by shariharan99** [comment] 2016-07-20 18:08
Happy to do it. What kind of session information do you want? I can't give full creds since there is sensitive data in our cloud, but I could try and replicate with a personal cloud?

**Comment by MarkEdmondson1234** [comment] 2016-07-20 18:44
The output of sessionInfo() is fine, it just shows what package versions and your OS. Also no need for credentials, but the r code that triggered the error and the type of file you were trying to download/upload is useful. I need to replicate it for best chance of fixing.
