### ISSUE TITLE
Request Status Code: 502

### ISSUE THREAD

**Issue by claudemeisch** [MarkEdmondson1234/googleAuthR#80] opened 2017-08-10 13:57 UTC
Hello, 
Thanks for the great package. I try to use it with the google vision API. But get Request Status Code: 502. Some error with a JSON content? It says no JSON content found. I cannot find any help on this? Any idea how the error is produced?
On windows x86-64, R version 3.4.0 (2017-04-21)

Any help greatly appreciated!! Thanks in advance

**Comment by MarkEdmondson1234** [comment] 2017-08-10 14:51
Thanks @claudemeisch - have you seen https://github.com/cloudyr/RoogleVision ? May take all the hard work for you.

**Comment by claudemeisch** [comment] 2017-08-24 08:59
Yes I tried it and it really makes it a lot easier. Thank you! However I still get this JSON message? Any ideas? What does it mean?
Sorry for the late reply.

**Comment by MarkEdmondson1234** [comment] 2017-08-24 12:19
Can you show some steps to reproduce the error?

**Comment by claudemeisch** [comment] 2017-08-24 12:42
So i do:
require(RoogleVision)
require(googleAuthR)
require(magrittr)

options("googleAuthR.client_id" = ....)
options("googleAuthR.client_secret" = ....) 
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/cloud-platform"))
googleAuthR::gar_auth()

Then i load a datatable with URL's of Flickr images which I want to classifiy. For this, i first read the datatable with Flickr <- data.table::fread (Flickr_data.csv) and then go

getGoogleVisionResponse(imagePath = Flickr$URL[i], feature="LANDMARK_DETECTION")

with Flickr$URL[i] being a string of characters

I get:
Request Status Code: 502
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
             (right here) ------^

Trying again: 1 of 5
Trying again: 2 of 5
Trying again: 3 of 5
Trying again: 4 of 5
Trying again: 5 of 5
Warning message:
No JSON content found in request

**Comment by claudemeisch** [comment] 2017-08-24 12:45
I try again. Something was missing
Request Status Code: 502
Error : lexical error: invalid char in json text.
                                      *smallerthansign*!DOCTYPE html> <html lang=en*greaterthansign*
                                      (right here) ------^

**Comment by MarkEdmondson1234** [comment] 2017-08-24 13:54
Probably best to open an issue here and point to this thread as its not I who has coded the details
https://github.com/cloudyr/RoogleVision/issues

To me it looks like you are passing in URLs when the library expects you to upload the image itself.

**Comment by MarkEdmondson1234** [comment] 2017-09-13 13:55
Closing this as another library specific issue.

**Closed by MarkEdmondson1234** 2017-09-13 13:55 UTC
